name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Build LimboAuth Social Addon
        run: ./gradlew build
      - name: Upload LimboAuth Social Addon
        uses: actions/upload-artifact@v2.3.1
        with:
          name: LimboAuth Social Addon Built On ${{ matrix.java }} JDK
          path: "build/libs/LimboAuth*.jar"
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: dev-build-jdk-${{ matrix.java }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release the build
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/LimboAuth*.jar"
          body: ${{ join(github.event.commits.*.message, '\n') }}
          prerelease: true
          name: JDK ${{ matrix.java }} Dev-build
          tag: dev-build-jdk-${{ matrix.java }}
